language = "English"

[main]
"version.now_on" = "Difficult Rocket is running on Python Vision"
"version.need3+" = "Difficult Rocket need Python vision 3.0+"
"version.best3.8+" = "Difficult Rocket is writen in Python {write_py_v}, and now is running on Python {py_v} may cause BUG"
"lang.language" = "English (EN-US)"
"logger.language" = "Logging language is: "
"logger.created" = "Log handler created"
"logger.mkdir" = "logs/ folder not found, now created"
"logger.main_done" = "Main log handler created "
"logger.logfile_name" = "Log file name :"
"logger.logfile_level" = "Log file record level :"
"logger.logfile_fmt" = "Log file record format :"
"logger.logfile_datefmt" = "Log file date format :"
"game_start.at" = "The main thread of the game starts with:"

[client]
"setup.done" = "Client load complete"
"setup.use_time" = "Client load use: {} second"
"setup.use_time_ns" = "Client load use: {} nano second"

[window]
"setup.done" = "Window load complete "
"setup.use_time" = "Window load use: {} second"
"setup.use_time_ns" = "Window load use: {} nano second"
"os.pid_is" = "Window's PID: {} PPID: {}"
"button.been_press" = "The button is pressed, the current state of the button is:"
"mouse.press_at" = "mouse was click at {} button is: {}"
"mouse.release" = "mouse release at {} button is: {}"
"mouse.RIGHT" = "right button"
"mouse.LEFT" = "left button"
"mouse.MIDDLE" = "middle button"
"key.press" = "key {} | {} been press"
"key.release" = "key {} | {} been release"
"text.input" = "input text \"{}\""
"text.new_line" = "new line"
"text.motion" = "text move {}"
"text.motion_select" = "text select {}"
"command.text" = "input command: {}"
"message.text" = "input message: {}"
"libs.local" = "using local pyglet, version: {}"
"libs.outer" = "using global pyglet, version: {}\n(may cause bug)"
"fonts.found" = "found fonts in font lib: {}"

[server]
"setup.done" = "Server load complete "
"os.pid_is" = "Server is using PID: {} PPID: {}"
