language = "简体中文"

[main]
"version.now_on" = "困难火箭的运行Python环境为"
"version.need3+" = "困难火箭需要Python3.0+的环境"
"version.best3.8+" = "困难火箭是在Python{write_py_v}的环境下编写的，目前正在运行在Python{py_v}的环境下，可能产生BUG"
"lang.language" = "简 体 中 文 （zh-cn）"
"logger.language" = "日志记录语言为："
"logger.created" = "日志处理器创建完成"
"logger.mkdir" = "logs/文件夹不存在，已经新建文件夹"
"logger.main_done" = "主日志处理器创建完成"
"logger.logfile_name" = "日志文件文件名："
"logger.logfile_level" = "日志文件记录级别："
"logger.logfile_fmt" = "日志文件记录格式："
"logger.logfile_datefmt" = "日志文件日期格式："
"game_start.at" = "游戏主线程开始于："

[client]
"setup.done" = "客户端载入完成"
"setup.use_time" = "客户端载入花费: {} 秒"
"setup.use_time_ns" = "客户端载入花费: {} 纳秒"

[window]
"setup.done" = "游戏窗口载入完成"
"setup.use_time" = "游戏窗口载入消耗时间: {} 秒"
"setup.use_time_ns" = "游戏窗口载入消耗时间: {} 纳秒"
"os.pid_is" = "游戏窗口 PID: {} PPID: {}"
"button.been_press" = "按钮被按下，目前状态为："
"mouse.press" = "鼠标在 {} 被按下，按键为：{}"
"mouse.release" = "鼠标在 {} 释放，按键为：{}"
"mouse.RIGHT" = "右键"
"mouse.LEFT" = "左键"
"mouse.MIDDLE" = "中键"
"key.press" = "按键 {} | {} 被按下"
"key.release" = "按键 {} | {} 被释放"
"text.input" = "输入字符 \"{}\""
"text.new_line" = "换行"
"text.motion" = "光标移动 {}"
"text.motion_select" = "光标选择 {}"
"command.text" = "输入命令: {}"
"message.text" = "输入信息: {}"
"libs.local" = "正在使用本地 pyglet 库 版本为: {}"
"libs.outer" = "正在使用全局 pyglet 库 版本为: {}\n(可能会造成bug，因为本地库版本为2.0dev9)"
"fonts.found" = "在字体列表中找到以下字体库: {}"
"fonts.load" = "正在加载字体: {}"
"game.input_stop" = "控制台"
"game.command_stop" = "游戏内命令行"
"game.window_stop" = "窗口"
"game.stop_get" = "从{}传入关闭指令,关闭游戏中"
"game.stop" = "游戏正在关闭,保存数据中···"
"game.end" = "游戏已经关闭"

[server]
"setup.done" = "服务端载入完成"
"os.pid_is" = "服务端 PID: {} PPID: {}"
